server {
    listen 80;

    location /hls/ {
        alias /hls/;
        add_header Access-Control-Allow-Origin * always;
        add_header Access-Control-Allow-Headers * always;

        location ~ \.m3u8$ {
            add_header Access-Control-Allow-Origin * always;
            add_header Cache-Control "no-cache, no-store" always;
            types { application/vnd.apple.mpegurl m3u8; }
        }
        location ~ \.ts$ {
            add_header Access-Control-Allow-Origin * always;
            add_header Cache-Control "max-age=60" always;
            types { video/mp2t ts; }
        }
    }

    location /healthz {
        return 200 '{"ok":true,"component":"origin"}';
        add_header Content-Type application/json;
    }
}
